number:
    path: /
    controller: App\controller\LuckyController::number

question_list:
    path: /questions
    controller: App\Controller\QuestionController::list

question_show:
    path: /questions/{slug}
    controller: App\Controller\QuestionController::show
