homepage:
    path: /
    controller: App\Controller\QuestionController::homepage

question_show:
    path: /questions/{slug}
    controller: App\Controller\QuestionController::show

commentVote:
    path: /comments/{id}/vote/{direction}
    controller: App\Controller\CommentController::commentVote
    requirements:
        id: '\d+'
        direction: 'up|down'
    methods: POST
